### PR TITLE
Glm/no macros

### PR DESCRIPTION
**Pull request by glehmannmiotto**
This PR is to remove the features of ERS that shall not be used directly by dune code anymore. The Logging package offers logging and debugging functionality through the underlying trace package.

### CODE REVIEW

**Comment by ron003** [comment]
The TRACE streamer macros (TLOG and TLOG_DEBUG) implement the slow path by using the following from directly from ers:
```
/home/ron/work/DUNEPrj/AD2021-02-20_ers/MyTopDir/sourcecode/logging/include
(dbt-pyvenv) ron@mu2edaq13 :^) find . -type f | xargs egrep 'ers::(debug|log)|ers::Debug|ers::Message'        
./logging/detail/Logger.hxx:            ers::log(   ers::Message(lc,outp) );
./logging/detail/Logger.hxx:            ers::debug( ers::Message(lc,outp),lvl-TLVL_DEBUG );
./logging/detail/Logger.hxx:            else if (x.lvl_==TLVL_LOG)  ers::log(   r );                                    \
./logging/detail/Logger.hxx:            else                        ers::debug( r, x.lvl_-TLVL_DEBUG ); \
./logging/detail/Logger.hxx:inline void operator<<(TraceStreamer& x, const ers::Message &r)
./logging/detail/Logger.hxx:            else if (x.lvl_==TLVL_LOG)  ers::log(   r );                                    \
./logging/detail/Logger.hxx:            else                        ers::debug( r, x.lvl_-TLVL_DEBUG ); \
./logging/detail/Logger.hxx:                                     else if (x.lvl_==TLVL_LOG)  ers::log(   r );           \
./logging/detail/Logger.hxx:                                     else                        ers::debug( r, x.lvl_-TLVL_DEBUG ); \
./logging/detail/Logger.hxx:                                     else if (x.lvl_==TLVL_LOG)  ers::log(   r );           \
./logging/detail/Logger.hxx:                                     else                        ers::debug( r, x.lvl_-TLVL_DEBUG ); \
./logging/detail/Logger.hxx:                    case ers::Debug:       lvl_=TLVL_DEBUG+sev.rank;break;
./logging/Logging.hpp:          // by only setting debug_level AFTER first ers::debug message
./logging/Logging.hpp:          ers::Message msg(lc,"Logger setup(...) ers::debug level 1 -- seems to come out level 0 (with ERS version v0_26_00d) ???");
./logging/Logging.hpp:          msg.set_severity( ers::Severity( ers::Debug, lvl ) );
./logging/Logging.hpp:          ers::debug(msg,lvl); // still comes out as level 0 ???
./logging/Logging.hpp:          ers::debug( ers::Message(lc,"Logger setup(...)"), 1 ); // comes out as DEBUG_0
--2021-02-20_20:41:41_CST--
```

My thought was that the dbt-build.sh --lint would flag direct uses of ers::Message, ers::log and ers::debug (similar to how the lint-ing currently flags uses of std::cout.
Yes, the macros ERS_{INFO,LOG,DEBUG} can be removed.

**Comment by alessandrothea** [comment]
@ron003 I'm confused, why does TRACE need to use `ers::debug` and `ers::log`? 
In my probably limited understanding, debug and log levels are supposed fully in the TRACE domain, aren't they?
From what I remember from our previous discussion, I would have expected that `ers::Message` could be dropped because LOG and DEBUG are not meant for the slow path? Is that wrong?

**Comment by ron003** [comment]
I'm sorry (and disappointed) there's confusion.

All along, I've tried to convey that TRACE does slow and fast logging and for the slow it can basically wrapper whatever logging one wants -- in this case ers.

So, for DEBUG, for example, people can select whether or not they want the message to go to either or both of the slow and fast, and if the slow is selected,
ers::debug is use. The default for the ers debug stream is stdout and therefore the message will be combined with other ers messages
which go to stdout -- all under ers control (i.e. ers formatted as per TDAQ_ERS_VERBOSITY_LEVEL).  As with the ERS_DEBUG macro, the Issue that gets passed to ers::debug is an ers::Message. That's the case for "general" (non-Issue) debug messages and also for general log level messages.
For the case where an Issue is streamed into either TLOG() or TLOG_DEBUG(lvl), the Issue is passed to ers::log or ers::debug.

This seems (or seemed) straight forward to me.

Based on your confusion, it seems you did not get that I was saying that ers was to be used for all "slow" logging?
I'm sorry I failed to get this message across :(    Is this a disaster?

**Comment by glehmannmiotto** [comment]
No disaster, of course.
So I will leave the debug/log streams in the ers package.
Since the only purpose of ers::Message is to create a specific ers issue around free text, which is something we clearly don’t want to suggest is a valid way of using ers, would it be possible to declare a ers issue inside the logging package, in a place that is not publicly installed that does exactly the same as ers::Message (called logging::Message) for the internal use of logging?

**Comment by alessandrothea** [comment]
Thanks for the clarification, @ron003. As @glehmannmiotto suggests, it would be good to remove `ers::Message` from the limelight. Unfortunately an equivalent logging `Issue` would remain public, as it needs to be accessible via the logging header, but it may be possible to confine it in a remote namespace. Another option would be to make it internal to the logger class, but I don't know how well ERS macro deal with being called inside a class declaration.

**Pull request closed without merging**
